apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wkc-iis-scc-rb
  namespace: {{ .Values.cpd_namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:wkc-iis-scc
subjects:
- kind: ServiceAccount
  name: wkc-iis-sa
  namespace: {{ .Values.cpd_namespace }}